name: Node.js Package

on:
  push: ~
  pull_request: ~

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        node-version: [12.x, 14.x]
        os: ['ubuntu-latest', 'windows-latest']

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Clean & build & lint
        run: npm run clean && npm run lint && npm run build

  release-drafter-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm run clean && npm run lint && npm run build
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yaml
          publish: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
